# Unified Docker Compose configuration with profiles for different environments
# Usage:
# - Default (x86_64): docker compose up -d
# - Docker (x86_64): ENVIRONMENT=docker docker compose --profile docker up -d
# - Raspberry Pi (ARM64): ENVIRONMENT=raspberry-pi TARGETARCH=arm64 DB_IMAGE=arm64v8/mariadb:10.6 DOCKERFILE=Dockerfile.arm64 docker compose --profile raspberry-pi up -d

services:
  db:
    profiles: [default, docker, raspberry-pi]
    image: ${DB_IMAGE:-mariadb:10.6}
    env_file:
      - .env.${ENVIRONMENT:-}
    environment:
      DOCKER_COMPOSE_ENV: ${ENVIRONMENT:-}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DB: ${MARIADB_DB}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./.env.${ENVIRONMENT:-}:/docker-entrypoint-initdb.d/.env.${ENVIRONMENT:-}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    networks:
      - taskquest-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MARIADB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  app:
    profiles: [default, docker, raspberry-pi]
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        - TARGETARCH=${TARGETARCH:-amd64}
    container_name: taskquest-app
    ports:
      - "${PORT:-8080}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${ENVIRONMENT:-}
    env_file:
      - .env.${ENVIRONMENT:-}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ${UPLOAD_DIR:-./uploads}:/app/uploads
    networks:
      - taskquest-network
    restart: unless-stopped

networks:
  taskquest-network:
    driver: bridge

volumes:
  db-data:
  uploads:
