version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.arm64
    ports:
      - "${PORT:-8080}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # Explicitly set database credentials to match those in init.sql
      MARIADB_USER: taskquest_user
      MARIADB_PASSWORD: secure_password
      MARIADB_HOST: db
      MARIADB_PORT: 3306
      MARIADB_DB: taskquest
    env_file:
      - .env.raspberry-pi
    volumes:
      - ${UPLOAD_DIR:-./uploads}:/app/uploads
    networks:
      - taskquest-network
    depends_on:
      db:
        condition: service_healthy


    restart: unless-stopped

  db:
    image: arm64v8/mariadb:10.6
    env_file:
      - .env.raspberry-pi
    environment:
      # Explicitly set database credentials to match those in init.sql
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DB: taskquest
      MARIADB_USER: taskquest_user
      MARIADB_PASSWORD: secure_password

    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - taskquest-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "taskquest_user", "-psecure_password" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s



networks:
  taskquest-network:
    driver: bridge

volumes:
  db-data:
  uploads:
