
services:
  db:
    image: mariadb:10.6

    env_file:
      - .env.docker
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DB}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MARIADB_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: taskquest-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - uploads:/app/uploads



volumes:
  db-data:
  uploads: