version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.arm64
    ports:
      - "${PORT:-8080}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # Use environment variables for database credentials
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    env_file:
      - .env.raspberry-pi
    volumes:
      - ${UPLOAD_DIR:-./uploads}:/app/uploads
    networks:
      - taskquest-network
    depends_on:
      db:
        condition: service_healthy


    restart: unless-stopped

  db:
    image: arm64v8/mariadb:10.6
    env_file:
      - .env.raspberry-pi
    environment:
      # Use environment variables for database credentials
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DB: ${MARIADB_DB}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql.template:/docker-entrypoint-initdb.d/init.sql.template
      - ./init-db.sh:/docker-entrypoint-initdb.d/00-init-db.sh
    entrypoint: ["sh", "-c", "chmod +x /docker-entrypoint-initdb.d/00-init-db.sh && /docker-entrypoint-initdb.d/00-init-db.sh"]
    restart: unless-stopped
    networks:
      - taskquest-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "taskquest_user", "-p${MARIADB_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s



networks:
  taskquest-network:
    driver: bridge

volumes:
  db-data:
  uploads:
