version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.arm64
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - .env.docker
    volumes:
      - ${UPLOAD_DIR:-./uploads}:/app/uploads
    networks:
      - taskquest-network
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: arm64v8/mariadb:10.6
    env_file:
      - .env.docker
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - taskquest-network


networks:
  taskquest-network:
    driver: bridge

volumes:
  db-data:

